In [5]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("data/raw")

In [6]:
orders = pd.read_csv(DATA_PATH / "orders.csv")
products = pd.read_csv(DATA_PATH / "products.csv")
aisles = pd.read_csv(DATA_PATH / "aisles.csv")
departments = pd.read_csv(DATA_PATH / "departments.csv")

In [7]:
display(orders.head())
display(products.head())
display(aisles.head())
display(departments.head())

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [9]:
orders.info()
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 198.9 MB
<class 'pandas.DataFrame'>
RangeIndex: 49688 entries, 0 to 49687
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49688 non-null  int64
 1   product_name   49688 non-null  str
 2   aisle_id       49688 non-null  int64
 3   department_id  49688 non-null  int64
dtypes: int64(3), str(1)
memory usage: 3.0 MB

In [10]:

aisles.info()
departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    str
dtypes: int64(1), str(1)
memory usage: 4.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 638.0 bytes

CHECK FOR EMPTY VALUES

In [16]:
print('Orders Nulls')
print(orders.isnull().sum())
print("\nProduct Nulls")
print(products.isnull().sum())

Orders Nulls
order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

Product Nulls
product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

CHECK FOR DUPLICATE VALUES

In [20]:
print("orders duplicates",orders.duplicated().sum())
print("PRODUCTS duplicates",products.duplicated().sum())
print("aisles duplicates",aisles.duplicated().sum())
print("Department duplicates",departments.duplicated().sum())

orders duplicates 0
PRODUCTS duplicates 0
aisles duplicates 0
Department duplicates 0

In [28]:
prior_sample=pd.read_csv(DATA_PATH / "order_products__prior.csv",nrows=10000)
train_sample=pd.read_csv(
    DATA_PATH / 
    "order_products__train.csv",
    nrows=10000
    )

In [29]:
print("Prior sample:", prior_sample.shape)
print("Train sample:", train_sample.shape)

display(prior_sample.head())
display(train_sample.head())

Prior sample: (10000, 4)
Train sample: (10000, 4)

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [31]:
def count_rows(file_path):
    with open(file_path, "r") as f:
        return sum(1 for _ in f) - 1

prior_rows = count_rows(DATA_PATH / "order_products__prior.csv")
train_rows = count_rows(DATA_PATH / "order_products__train.csv")

print("Prior rows:", prior_rows)
print("Train rows:", train_rows)

Prior rows: 32434489
Train rows: 1384617

In [32]:
print("Unique users:", orders["user_id"].nunique())
print("Unique orders:", orders["order_id"].nunique())
print("Unique products:", products["product_id"].nunique())
print("Departments:", departments["department_id"].nunique())
print("Aisles:", aisles["aisle_id"].nunique())

Unique users: 206209
Unique orders: 3421083
Unique products: 49688
Departments: 21
Aisles: 134

In [33]:
print(orders.columns.tolist())
print(products.columns.tolist())
print(aisles.columns.tolist())
print(departments.columns.tolist())
print(prior_sample.columns.tolist())
print(train_sample.columns.tolist())

['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order']
['product_id', 'product_name', 'aisle_id', 'department_id']
['aisle_id', 'aisle']
['department_id', 'department']
['order_id', 'product_id', 'add_to_cart_order', 'reordered']
['order_id', 'product_id', 'add_to_cart_order', 'reordered']

In [35]:
orders["eval_set"].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [36]:
orders.groupby("user_id")["order_number"].max().describe()

count    206209.000000
mean         16.590367
std          16.654774
min           4.000000
25%           6.000000
50%          10.000000
75%          20.000000
max         100.000000
Name: order_number, dtype: float64

day of week order details

In [40]:
orders["order_dow"].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

hour of order details

In [38]:
orders["order_hour_of_day"].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

creating silver layer

In [41]:
products_silver=products.copy()
aisles_silver=aisles.copy()
departments_silver=departments.copy()

In [42]:
products_silver.columns = products_silver.columns.str.strip().str.lower()
aisles_silver.columns = aisles_silver.columns.str.strip().str.lower()
departments_silver.columns = departments_silver.columns.str.strip().str.lower()

In [43]:
print("Products duplicates:", products_silver.duplicated().sum())
print("Aisles duplicates:", aisles_silver.duplicated().sum())
print("Departments duplicates:", departments_silver.duplicated().sum())

Products duplicates: 0
Aisles duplicates: 0
Departments duplicates: 0

In [44]:
products_silver=products_silver.drop_duplicates()
aisles_silver=aisles_silver.drop_duplicates()
departments_silver=departments_silver.drop_duplicates()

In [45]:
print("Products nulls:",products_silver.isnull().sum())
print("Products nulls:",aisles_silver.isnull().sum())
print("Products nulls:",departments_silver.isnull().sum())

Products nulls: product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64
Products nulls: aisle_id    0
aisle       0
dtype: int64
Products nulls: department_id    0
department       0
dtype: int64

In [46]:
print("product_id unique:", products_silver["product_id"].is_unique)
print("aisle_id unique:", aisles_silver["aisle_id"].is_unique)
print("department_id unique:", departments_silver["department_id"].is_unique)

product_id unique: True
aisle_id unique: True
department_id unique: True

Check for every aisle id is present in products table or not

In [50]:
invalid_aisles=products_silver[
    ~products_silver["aisle_id"].isin(aisles_silver["aisle_id"])
]
print("invalid aisles references",len(invalid_aisles))

invalid aisles references 0

check for every department id that is there in products table should be  in  departments

In [52]:
invalid_departments=products_silver[
    ~products_silver["department_id"].isin(departments_silver["department_id"])
]
print("invalid aisles references",len(invalid_departments))

invalid aisles references 0

join the products aisles and departments table

In [55]:
products_enriched=(products_silver
.merge(
    aisles_silver,
    on="aisle_id",
    how="left"
)
.merge(
    departments_silver,
    on="department_id",
    how="left"
)
)
print(products_enriched.head())

   product_id                                       product_name  aisle_id  \
0           1                         Chocolate Sandwich Cookies        61
1           2                                   All-Seasons Salt       104
2           3               Robust Golden Unsweetened Oolong Tea        94
3           4  Smart Ones Classic Favorites Mini Rigatoni Wit...        38
4           5                          Green Chile Anytime Sauce         5

   department_id                       aisle department
0             19               cookies cakes     snacks
1             13           spices seasonings     pantry
2              7                         tea  beverages
3              1                frozen meals     frozen
4             13  marinades meat preparation     pantry

In [56]:
print(products_enriched.shape)

(49688, 6)

Saving the file as parquet

In [57]:
from pathlib import Path

SILVER_PATH = Path("data/silver")
SILVER_PATH.mkdir(parents=True, exist_ok=True)

products_enriched.to_parquet(
    SILVER_PATH / "products_enriched.parquet",
    index=False
)

In [58]:
print(list(SILVER_PATH.iterdir()))

[PosixPath('data/silver/products_enriched.parquet')]

WE will create an silver layer for orders

In [59]:
orders_silver=orders.copy()

In [64]:
orders_silver.columns=orders_silver.columns.str.strip().str.lower()
orders_silver.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [68]:
print("Duplicates Rows",orders_silver.duplicated().sum())
print("duplicated order ids",orders_silver["order_id"].duplicated().sum())

Duplicates Rows 0
duplicated order ids 0

In [70]:
print("Null Values",orders_silver.isnull().sum())

Null Values order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

we noticed null values in day_since_prior_order because there would be no values if a person orders for the first time,so we check for first orders to match the numbers

In [72]:
first_orders=orders_silver[orders_silver["order_number"]==1]
print("num of first orders",len(first_orders))
print("first orders with missing dates",orders_silver["days_since_prior_order"].isnull().sum())

num of first orders 206209
first orders with missing dates 206209

In [73]:
orders_silver["eval_set"].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [74]:
print(
    orders_silver["eval_set"]
    .isin(["prior", "train", "test"])
    .all()
)

True

validate the date of week should be between 0 and 6

In [76]:
print("Order_DOW range",orders_silver["order_dow"].min(),
"-",orders_silver["order_dow"].max())

Order_DOW range 0 - 6

we can clearly see all the values are between 0-6,now we need to validate order hours they should be between 0 and 23

In [77]:
print("Order_Hour range",orders_silver["order_hour_of_day"].min(),
"-",orders_silver["order_hour_of_day"].max())

Order_Hour range 0 - 23

Now we need to check for order number they should increase sequentially

In [80]:
order_check=(orders_silver.sort_values(["user_id","order_number"])
.groupby("user_id")["order_number"]
.agg(["min","max","count"]))
order_check.head(10)

         min  max  count
user_id
1          1   11     11
2          1   15     15
3          1   13     13
4          1    6      6
5          1    5      5
6          1    4      4
7          1   21     21
8          1    4      4
9          1    4      4
10         1    6      6

Add new column to flag customers first orders

In [83]:
orders_silver["is_first_order"] = (
    orders_silver["order_number"] == 1
).astype("int8")

add other column to flag not first order

In [86]:
orders_silver["is_repeat_order"] = (
    orders_silver["order_number"]> 1
).astype("int8")

apply time of day using order_hour_of_day

In [88]:
def get_time_period(hour):
    if 5<= hour <12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

orders_silver["time_period"]=orders_silver["order_hour_of_day"].apply(get_time_period)

orders_silver.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_first_order,is_repeat_order,time_period
0,2539329,1,prior,1,2,8,NaN,1,0,Morning
1,2398795,1,prior,2,3,7,15.0,0,1,Morning
2,473747,1,prior,3,3,12,21.0,0,1,Afternoon
3,2254736,1,prior,4,4,7,29.0,0,1,Morning
4,431534,1,prior,5,4,15,28.0,0,1,Afternoon

Check the shape from start of orders silver layer to now,you can see same rows but extra three columns

In [89]:
print("Original:", orders.shape)
print("Silver:", orders_silver.shape)

Original: (3421083, 7)
Silver: (3421083, 10)

save to silver layer in parquet form

In [90]:
orders_silver.to_parquet(SILVER_PATH/"orders_clean_parquet",index="False")

In [91]:
from pathlib import Path

PRIOR_CSV = DATA_PATH / "order_products__prior.csv"
PRIOR_PARQUET_DIR = SILVER_PATH / "order_products_prior"

PRIOR_PARQUET_DIR.mkdir(parents=True, exist_ok=True)

In [92]:
import pandas as pd

chunk_number = 0
total_rows = 0
CHUNK_SIZE=500000

for chunk in pd.read_csv(PRIOR_CSV, chunksize=CHUNK_SIZE):

    chunk_number += 1

    # Standardize column names
    chunk.columns = chunk.columns.str.strip().str.lower()

    # Remove exact duplicate rows
    chunk = chunk.drop_duplicates()

    # Validate reordered
    chunk = chunk[
        chunk["reordered"].isin([0, 1])
    ]

    # Validate cart position
    chunk = chunk[
        chunk["add_to_cart_order"] > 0
    ]

    # Save each chunk as a separate parquet file
    output_file = (
        PRIOR_PARQUET_DIR /
        f"part_{chunk_number:03d}.parquet"
    )

    chunk.to_parquet(
        output_file,
        index=False
    )

    total_rows += len(chunk)

    print(
        f"Chunk {chunk_number} completed | "
        f"Rows written: {len(chunk):,} | "
        f"Total: {total_rows:,}"
    )

Chunk 1 completed | Rows written: 500,000 | Total: 500,000
Chunk 2 completed | Rows written: 500,000 | Total: 1,000,000
Chunk 3 completed | Rows written: 500,000 | Total: 1,500,000
Chunk 4 completed | Rows written: 500,000 | Total: 2,000,000
Chunk 5 completed | Rows written: 500,000 | Total: 2,500,000
Chunk 6 completed | Rows written: 500,000 | Total: 3,000,000
Chunk 7 completed | Rows written: 500,000 | Total: 3,500,000
Chunk 8 completed | Rows written: 500,000 | Total: 4,000,000
Chunk 9 completed | Rows written: 500,000 | Total: 4,500,000
Chunk 10 completed | Rows written: 500,000 | Total: 5,000,000
Chunk 11 completed | Rows written: 500,000 | Total: 5,500,000
Chunk 12 completed | Rows written: 500,000 | Total: 6,000,000
Chunk 13 completed | Rows written: 500,000 | Total: 6,500,000
Chunk 14 completed | Rows written: 500,000 | Total: 7,000,000
Chunk 15 completed | Rows written: 500,000 | Total: 7,500,000
Chunk 16 completed | Rows written: 500,000 | Total: 8,000,000
Chunk 17 completed | Rows written: 500,000 | Total: 8,500,000
Chunk 18 completed | Rows written: 500,000 | Total: 9,000,000
Chunk 19 completed | Rows written: 500,000 | Total: 9,500,000
Chunk 20 completed | Rows written: 500,000 | Total: 10,000,000
Chunk 21 completed | Rows written: 500,000 | Total: 10,500,000
Chunk 22 completed | Rows written: 500,000 | Total: 11,000,000
Chunk 23 completed | Rows written: 500,000 | Total: 11,500,000
Chunk 24 completed | Rows written: 500,000 | Total: 12,000,000
Chunk 25 completed | Rows written: 500,000 | Total: 12,500,000
Chunk 26 completed | Rows written: 500,000 | Total: 13,000,000
Chunk 27 completed | Rows written: 500,000 | Total: 13,500,000
Chunk 28 completed | Rows written: 500,000 | Total: 14,000,000
Chunk 29 completed | Rows written: 500,000 | Total: 14,500,000
Chunk 30 completed | Rows written: 500,000 | Total: 15,000,000
Chunk 31 completed | Rows written: 500,000 | Total: 15,500,000
Chunk 32 completed | Rows written: 500,000 | Total: 16,000,000
Chunk 33 completed | Rows written: 500,000 | Total: 16,500,000
Chunk 34 completed | Rows written: 500,000 | Total: 17,000,000
Chunk 35 completed | Rows written: 500,000 | Total: 17,500,000
Chunk 36 completed | Rows written: 500,000 | Total: 18,000,000
Chunk 37 completed | Rows written: 500,000 | Total: 18,500,000
Chunk 38 completed | Rows written: 500,000 | Total: 19,000,000
Chunk 39 completed | Rows written: 500,000 | Total: 19,500,000
Chunk 40 completed | Rows written: 500,000 | Total: 20,000,000
Chunk 41 completed | Rows written: 500,000 | Total: 20,500,000
Chunk 42 completed | Rows written: 500,000 | Total: 21,000,000
Chunk 43 completed | Rows written: 500,000 | Total: 21,500,000
Chunk 44 completed | Rows written: 500,000 | Total: 22,000,000
Chunk 45 completed | Rows written: 500,000 | Total: 22,500,000
Chunk 46 completed | Rows written: 500,000 | Total: 23,000,000
Chunk 47 completed | Rows written: 500,000 | Total: 23,500,000
Chunk 48 completed | Rows written: 500,000 | Total: 24,000,000
Chunk 49 completed | Rows written: 500,000 | Total: 24,500,000
Chunk 50 completed | Rows written: 500,000 | Total: 25,000,000
Chunk 51 completed | Rows written: 500,000 | Total: 25,500,000
Chunk 52 completed | Rows written: 500,000 | Total: 26,000,000
Chunk 53 completed | Rows written: 500,000 | Total: 26,500,000
Chunk 54 completed | Rows written: 500,000 | Total: 27,000,000
Chunk 55 completed | Rows written: 500,000 | Total: 27,500,000
Chunk 56 completed | Rows written: 500,000 | Total: 28,000,000
Chunk 57 completed | Rows written: 500,000 | Total: 28,500,000
Chunk 58 completed | Rows written: 500,000 | Total: 29,000,000
Chunk 59 completed | Rows written: 500,000 | Total: 29,500,000
Chunk 60 completed | Rows written: 500,000 | Total: 30,000,000
Chunk 61 completed | Rows written: 500,000 | Total: 30,500,000
Chunk 62 completed | Rows written: 500,000 | Total: 31,000,000
Chunk 63 completed | Rows written: 500,000 | Total: 31,500,000
Chunk 64 completed | Rows written: 500,000 | Total: 32,000,000
Chunk 65 completed | Rows written: 434,489 | Total: 32,434,489

In [93]:
parquet_files=list(PRIOR_PARQUET_DIR.glob("*.parquet"))

print("Parquet FIles created",len(parquet_files))

Parquet FIles created 65

In [96]:
test_prior=pd.read_parquet(parquet_files[0])

print(test_prior.shape)
print(test_prior.head(10))
test_prior.info()

(500000, 4)
   order_id  product_id  add_to_cart_order  reordered
0   2003890       46194                  2          0
1   2003890        7862                  3          0
2   2003890       43867                  4          0
3   2003891       21195                  1          1
4   2003892       27845                  1          1
5   2003893       46842                  1          1
6   2003893        4006                  2          1
7   2003893       45566                  3          0
8   2003893       39858                  4          0
9   2003893       45531                  5          0
<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   order_id           500000 non-null  int64
 1   product_id         500000 non-null  int64
 2   add_to_cart_order  500000 non-null  int64
 3   reordered          500000 non-null  int64
dtypes: int64(4)
memory usage: 15.3 MB

check basic validity for add_to_cart and reordered

In [97]:
print(
    "Invalid reordered values:",
    (~test_prior["reordered"].isin([0, 1])).sum()
)

print(
    "Invalid cart positions:",
    (test_prior["add_to_cart_order"] <= 0).sum()
)

Invalid reordered values: 0
Invalid cart positions: 0

In [ ]:
TRAIN_CSV = DATA_PATH / "order_products__train.csv"

TRAIN_PARQUET_DIR = SILVER_PATH / "order_products_train"

TRAIN_PARQUET_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [98]:
TRAIN_CSV = DATA_PATH / "order_products__train.csv"

TRAIN_PARQUET_DIR = SILVER_PATH / "order_products_train"

TRAIN_PARQUET_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [99]:
CHUNK_SIZE = 500_000

chunk_number = 0
total_rows = 0

for chunk in pd.read_csv(
    TRAIN_CSV,
    chunksize=CHUNK_SIZE
):

    chunk_number += 1

    chunk.columns = (
        chunk.columns
        .str.strip()
        .str.lower()
    )

    # Remove exact duplicates
    chunk = chunk.drop_duplicates()

    # Validate reordered
    chunk = chunk[
        chunk["reordered"].isin([0, 1])
    ]

    # Validate cart position
    chunk = chunk[
        chunk["add_to_cart_order"] > 0
    ]

    output_file = (
        TRAIN_PARQUET_DIR /
        f"part_{chunk_number:03d}.parquet"
    )

    chunk.to_parquet(
        output_file,
        index=False
    )

    total_rows += len(chunk)

    print(
        f"Chunk {chunk_number} completed | "
        f"Rows written: {len(chunk):,} | "
        f"Total: {total_rows:,}"
    )

Chunk 1 completed | Rows written: 500,000 | Total: 500,000
Chunk 2 completed | Rows written: 500,000 | Total: 1,000,000
Chunk 3 completed | Rows written: 384,617 | Total: 1,384,617

In [100]:
train_parquet_files = list(
    TRAIN_PARQUET_DIR.glob("*.parquet")
)

print(
    "Train parquet files:",
    len(train_parquet_files)
)

Train parquet files: 3

In [101]:
train_test = pd.read_parquet(
    train_parquet_files[0]
)

print(train_test.shape)

display(
    train_test.head()
)

(500000, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

now we will create an combine table with prior and train data and create a new column which will let us know the data is from which table

In [102]:
FACT_DIR = (
    SILVER_PATH /
    "order_products_fact"
)

FACT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [103]:
prior_files = sorted(
    PRIOR_PARQUET_DIR.glob("*.parquet")
)

for i, file in enumerate(
    prior_files,
    start=1
):

    df = pd.read_parquet(file)

    df["source_set"] = "prior"

    df.to_parquet(
        FACT_DIR /
        f"prior_part_{i:03d}.parquet",
        index=False
    )

print("Prior fact files completed")

Prior fact files completed

In [104]:
train_files = sorted(
    TRAIN_PARQUET_DIR.glob("*.parquet")
)

for i, file in enumerate(
    train_files,
    start=1
):

    df = pd.read_parquet(file)

    df["source_set"] = "train"

    df.to_parquet(
        FACT_DIR /
        f"train_part_{i:03d}.parquet",
        index=False
    )

print("Train fact files completed")

Train fact files completed

In [108]:
sample_fact = pd.read_parquet(
    sorted(
        FACT_DIR.glob("*.parquet")
    )[0]
)

display(sample_fact.head(10))

   order_id  product_id  add_to_cart_order  reordered source_set
0         2       33120                  1          1      prior
1         2       28985                  2          1      prior
2         2        9327                  3          0      prior
3         2       45918                  4          1      prior
4         2       30035                  5          0      prior
5         2       17794                  6          1      prior
6         2       40141                  7          1      prior
7         2        1819                  8          1      prior
8         2       43668                  9          0      prior
9         3       33754                  1          1      prior

In [111]:
print(
    sample_fact[
        "source_set"
    ].value_counts()
)

source_set
prior    500000
Name: count, dtype: int64

In [113]:
ANALYTICS_SILVER_DIR = SILVER_PATH / "analytics_ready"

ANALYTICS_SILVER_DIR.mkdir(parents=True,exist_ok=True)

In [118]:
orders_lookup=pd.read_parquet(SILVER_PATH / "orders_clean.parquet")
products_lookup=pd.read_parquet(SILVER_PATH / "products_enriched.parquet")

print("ORDERS SHAPE",orders_lookup.shape)
print("PRODUCTS SHAPE",products_lookup.shape)

ORDERS SHAPE (3421083, 10)
PRODUCTS SHAPE (49688, 6)

In [119]:
fact_files = sorted(
    FACT_DIR.glob("*.parquet")
)

print("Fact files:", len(fact_files))

Fact files: 68

Now we will merge actual silver layer for analytics

In [124]:
total_rows_written=0
for i,file in enumerate(fact_files,start=1):
    fact_chunk = pd.read_parquet(file)
    merged = fact_chunk.merge(
        orders_lookup[
        [
            "order_id",
            "user_id",
            "order_number",
            "order_dow",
            "order_hour_of_day",
            "days_since_prior_order",
            "is_first_order",
            "is_repeat_order",	"time_period"

             ]
        ],on ="order_id",how="left"
    )
merged=merged.merge(products_lookup[
    [
        "product_id",
        "product_name",
        "aisle_id",
        "aisle",
        "department_id",
        "department"
    ]
],on="product_id",how="left")   
output_file = (
        ANALYTICS_SILVER_DIR /
        f"analytics_part_{i:03d}.parquet"
    )

merged.to_parquet(
        output_file,
        index=False
    )

total_rows_written += len(merged)

print(
        f"File {i} completed | "
        f"Rows: {len(merged):,} | "
        f"Total: {total_rows_written:,}"
    )

File 68 completed | Rows: 384,617 | Total: 384,617

In [128]:
analytics_files = sorted(ANALYTICS_SILVER_DIR.glob("*.parquet"))

print("ANALYTICS CREATEd", len(analytics_files))

sample_analytics=pd.read_parquet(analytics_files[0])
display(sample_analytics.head(10))

ANALYTICS CREATEd 1

,order_id,product_id,add_to_cart_order,reordered,source_set,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_first_order,is_repeat_order,time_period,product_name,aisle_id,aisle,department_id,department
0,2470483,7170,5,1,train,92353,5,1,12,30.0,0,1,Afternoon,Dark Magic Extra Bold Dark Roast Coffee K Cups,26,coffee,7,beverages
1,2470483,32980,6,0,train,92353,5,1,12,30.0,0,1,Afternoon,"Mini I.D.'s French Vanilla Creamer, Singles",53,cream,16,dairy eggs
2,2470483,48249,7,0,train,92353,5,1,12,30.0,0,1,Afternoon,Hazelnut Creamer,6,other,2,other
3,2470483,10641,8,0,train,92353,5,1,12,30.0,0,1,Afternoon,Iced Coffee Sweet & Creamy Coffee House Drink,26,coffee,7,beverages
4,2470483,27864,9,0,train,92353,5,1,12,30.0,0,1,Afternoon,Butter Croissant,93,breakfast bakery,3,bakery
5,2470506,13176,1,1,train,196914,8,1,9,15.0,0,1,Morning,Bag of Organic Bananas,24,fresh fruits,4,produce
6,2470506,41065,2,1,train,196914,8,1,9,15.0,0,1,Morning,Organic Yellow Squash,83,fresh vegetables,4,produce
7,2470506,45007,3,1,train,196914,8,1,9,15.0,0,1,Morning,Organic Zucchini,83,fresh vegetables,4,produce
8,2470506,15872,4,1,train,196914,8,1,9,15.0,0,1,Morning,Celery Hearts,83,fresh vegetables,4,produce
9,2470506,11182,5,1,train,196914,8,1,9,15.0,0,1,Morning,Baby Spinach,123,packaged vegetables fruits,4,produce

In [130]:
import shutil

if ANALYTICS_SILVER_DIR.exists():
    shutil.rmtree(ANALYTICS_SILVER_DIR)

ANALYTICS_SILVER_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("Analytics folder reset")

Analytics folder reset

In [131]:
fact_files = sorted(
    FACT_DIR.glob("*.parquet")
)

total_rows_written = 0

for i, file in enumerate(fact_files, start=1):

    print(f"Processing file {i}/{len(fact_files)}")

    fact_chunk = pd.read_parquet(file)

    # Join order information
    merged = fact_chunk.merge(
        orders_lookup[
            [
                "order_id",
                "user_id",
                "order_number",
                "order_dow",
                "order_hour_of_day",
                "days_since_prior_order",
                "is_first_order",
                "is_repeat_order",
                "time_period"
            ]
        ],
        on="order_id",
        how="left"
    )

    # Join product information
    merged = merged.merge(
        products_lookup[
            [
                "product_id",
                "product_name",
                "aisle_id",
                "aisle",
                "department_id",
                "department"
            ]
        ],
        on="product_id",
        how="left"
    )

    

    output_file = (
        ANALYTICS_SILVER_DIR /
        f"analytics_part_{i:03d}.parquet"
    )

    merged.to_parquet(
        output_file,
        index=False
    )

    total_rows_written += len(merged)

    print(
        f"File {i} completed | "
        f"Rows: {len(merged):,} | "
        f"Running Total: {total_rows_written:,}"
    )

Processing file 1/68
File 1 completed | Rows: 500,000 | Running Total: 500,000
Processing file 2/68
File 2 completed | Rows: 500,000 | Running Total: 1,000,000
Processing file 3/68
File 3 completed | Rows: 500,000 | Running Total: 1,500,000
Processing file 4/68
File 4 completed | Rows: 500,000 | Running Total: 2,000,000
Processing file 5/68
File 5 completed | Rows: 500,000 | Running Total: 2,500,000
Processing file 6/68
File 6 completed | Rows: 500,000 | Running Total: 3,000,000
Processing file 7/68
File 7 completed | Rows: 500,000 | Running Total: 3,500,000
Processing file 8/68
File 8 completed | Rows: 500,000 | Running Total: 4,000,000
Processing file 9/68
File 9 completed | Rows: 500,000 | Running Total: 4,500,000
Processing file 10/68
File 10 completed | Rows: 500,000 | Running Total: 5,000,000
Processing file 11/68
File 11 completed | Rows: 500,000 | Running Total: 5,500,000
Processing file 12/68
File 12 completed | Rows: 500,000 | Running Total: 6,000,000
Processing file 13/68
File 13 completed | Rows: 500,000 | Running Total: 6,500,000
Processing file 14/68
File 14 completed | Rows: 500,000 | Running Total: 7,000,000
Processing file 15/68
File 15 completed | Rows: 500,000 | Running Total: 7,500,000
Processing file 16/68
File 16 completed | Rows: 500,000 | Running Total: 8,000,000
Processing file 17/68
File 17 completed | Rows: 500,000 | Running Total: 8,500,000
Processing file 18/68
File 18 completed | Rows: 500,000 | Running Total: 9,000,000
Processing file 19/68
File 19 completed | Rows: 500,000 | Running Total: 9,500,000
Processing file 20/68
File 20 completed | Rows: 500,000 | Running Total: 10,000,000
Processing file 21/68
File 21 completed | Rows: 500,000 | Running Total: 10,500,000
Processing file 22/68
File 22 completed | Rows: 500,000 | Running Total: 11,000,000
Processing file 23/68
File 23 completed | Rows: 500,000 | Running Total: 11,500,000
Processing file 24/68
File 24 completed | Rows: 500,000 | Running Total: 12,000,000
Processing file 25/68
File 25 completed | Rows: 500,000 | Running Total: 12,500,000
Processing file 26/68
File 26 completed | Rows: 500,000 | Running Total: 13,000,000
Processing file 27/68
File 27 completed | Rows: 500,000 | Running Total: 13,500,000
Processing file 28/68
File 28 completed | Rows: 500,000 | Running Total: 14,000,000
Processing file 29/68
File 29 completed | Rows: 500,000 | Running Total: 14,500,000
Processing file 30/68
File 30 completed | Rows: 500,000 | Running Total: 15,000,000
Processing file 31/68
File 31 completed | Rows: 500,000 | Running Total: 15,500,000
Processing file 32/68
File 32 completed | Rows: 500,000 | Running Total: 16,000,000
Processing file 33/68
File 33 completed | Rows: 500,000 | Running Total: 16,500,000
Processing file 34/68
File 34 completed | Rows: 500,000 | Running Total: 17,000,000
Processing file 35/68
File 35 completed | Rows: 500,000 | Running Total: 17,500,000
Processing file 36/68
File 36 completed | Rows: 500,000 | Running Total: 18,000,000
Processing file 37/68
File 37 completed | Rows: 500,000 | Running Total: 18,500,000
Processing file 38/68
File 38 completed | Rows: 500,000 | Running Total: 19,000,000
Processing file 39/68
File 39 completed | Rows: 500,000 | Running Total: 19,500,000
Processing file 40/68
File 40 completed | Rows: 500,000 | Running Total: 20,000,000
Processing file 41/68
File 41 completed | Rows: 500,000 | Running Total: 20,500,000
Processing file 42/68
File 42 completed | Rows: 500,000 | Running Total: 21,000,000
Processing file 43/68
File 43 completed | Rows: 500,000 | Running Total: 21,500,000
Processing file 44/68
File 44 completed | Rows: 500,000 | Running Total: 22,000,000
Processing file 45/68
File 45 completed | Rows: 500,000 | Running Total: 22,500,000
Processing file 46/68
File 46 completed | Rows: 500,000 | Running Total: 23,000,000
Processing file 47/68
File 47 completed | Rows: 500,000 | Running Total: 23,500,000
Processing file 48/68
File 48 completed | Rows: 500,000 | Running Total: 24,000,000
Processing file 49/68
File 49 completed | Rows: 500,000 | Running Total: 24,500,000
Processing file 50/68
File 50 completed | Rows: 500,000 | Running Total: 25,000,000
Processing file 51/68
File 51 completed | Rows: 500,000 | Running Total: 25,500,000
Processing file 52/68
File 52 completed | Rows: 500,000 | Running Total: 26,000,000
Processing file 53/68
File 53 completed | Rows: 500,000 | Running Total: 26,500,000
Processing file 54/68
File 54 completed | Rows: 500,000 | Running Total: 27,000,000
Processing file 55/68
File 55 completed | Rows: 500,000 | Running Total: 27,500,000
Processing file 56/68
File 56 completed | Rows: 500,000 | Running Total: 28,000,000
Processing file 57/68
File 57 completed | Rows: 500,000 | Running Total: 28,500,000
Processing file 58/68
File 58 completed | Rows: 500,000 | Running Total: 29,000,000
Processing file 59/68
File 59 completed | Rows: 500,000 | Running Total: 29,500,000
Processing file 60/68
File 60 completed | Rows: 500,000 | Running Total: 30,000,000
Processing file 61/68
File 61 completed | Rows: 500,000 | Running Total: 30,500,000
Processing file 62/68
File 62 completed | Rows: 500,000 | Running Total: 31,000,000
Processing file 63/68
File 63 completed | Rows: 500,000 | Running Total: 31,500,000
Processing file 64/68
File 64 completed | Rows: 500,000 | Running Total: 32,000,000
Processing file 65/68
File 65 completed | Rows: 434,489 | Running Total: 32,434,489
Processing file 66/68
File 66 completed | Rows: 500,000 | Running Total: 32,934,489
Processing file 67/68
File 67 completed | Rows: 500,000 | Running Total: 33,434,489
Processing file 68/68
File 68 completed | Rows: 384,617 | Running Total: 33,819,106

In [133]:
analytics_files = sorted(
    ANALYTICS_SILVER_DIR.glob("*.parquet")
)

print("Analytics files:", len(analytics_files))

Analytics files: 68

NOW WE ARE READY TO CREATE GOLD LAYER

In [136]:
GOLD_PATH=Path("data/gold")

GOLD_PATH.mkdir(parents=True,exist_ok=True)

In [147]:
product_parts = []
for i, file in enumerate(analytics_files,start=1):
    df = pd.read_parquet(file,columns=[
            "product_id",
            "product_name",
            "department",
            "aisle",
            "order_id",
            "user_id",
            "reordered",
            "add_to_cart_order"
            ])

    product_summary=(df.groupby([
        "product_id",
        "product_name",
        "department",
        "aisle"
    
    ],as_index=False
    ).agg(
        total_purchases=("order_id","count"),
        unique_orders=("order_id","nunique"),
        unique_customers=("user_id","nunique"),
        reorder_count=("reordered","sum"),
        avg_cart_position=("add_to_cart_order","mean")

    )  
)    
    product_parts.append(product_summary)

    print(f"Processed file {i}/{len(analytics_files)}")

Processed file 1/68
Processed file 2/68
Processed file 3/68
Processed file 4/68
Processed file 5/68
Processed file 6/68
Processed file 7/68
Processed file 8/68
Processed file 9/68
Processed file 10/68
Processed file 11/68
Processed file 12/68
Processed file 13/68
Processed file 14/68
Processed file 15/68
Processed file 16/68
Processed file 17/68
Processed file 18/68
Processed file 19/68
Processed file 20/68
Processed file 21/68
Processed file 22/68
Processed file 23/68
Processed file 24/68
Processed file 25/68
Processed file 26/68
Processed file 27/68
Processed file 28/68
Processed file 29/68
Processed file 30/68
Processed file 31/68
Processed file 32/68
Processed file 33/68
Processed file 34/68
Processed file 35/68
Processed file 36/68
Processed file 37/68
Processed file 38/68
Processed file 39/68
Processed file 40/68
Processed file 41/68
Processed file 42/68
Processed file 43/68
Processed file 44/68
Processed file 45/68
Processed file 46/68
Processed file 47/68
Processed file 48/68
Processed file 49/68
Processed file 50/68
Processed file 51/68
Processed file 52/68
Processed file 53/68
Processed file 54/68
Processed file 55/68
Processed file 56/68
Processed file 57/68
Processed file 58/68
Processed file 59/68
Processed file 60/68
Processed file 61/68
Processed file 62/68
Processed file 63/68
Processed file 64/68
Processed file 65/68
Processed file 66/68
Processed file 67/68
Processed file 68/68

In [148]:
product_all = pd.concat(
    product_parts,
    ignore_index=True
)

print("Combined partial rows:", product_all.shape)

display(product_all.head())

Combined partial rows: (1982579, 9)

,product_id,product_name,department,aisle,total_purchases,unique_orders,unique_customers,reorder_count,avg_cart_position
0,1,Chocolate Sandwich Cookies,snacks,cookies cakes,37,37,36,25,5.702703
1,2,All-Seasons Salt,pantry,spices seasonings,1,1,1,0,20.000000
2,3,Robust Golden Unsweetened Oolong Tea,beverages,tea,3,3,3,2,3.000000
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,frozen,frozen meals,4,4,4,2,7.500000
4,9,Light Strawberry Blueberry Yogurt,dairy eggs,yogurt,1,1,1,1,15.000000

In [149]:
product_all["cart_position_total"] = (
    product_all["avg_cart_position"]
    *
    product_all["total_purchases"]
)

In [150]:
gold_product_performance = (
    product_all
    .groupby(
        [
            "product_id",
            "product_name",
            "department",
            "aisle"
        ],
        as_index=False
    )
    .agg(
        total_purchases=("total_purchases", "sum"),
        reorder_count=("reorder_count", "sum"),
        cart_position_total=("cart_position_total", "sum")
    )
)

In [151]:
gold_product_performance["reorder_rate"] = (
    gold_product_performance["reorder_count"]
    /
    gold_product_performance["total_purchases"]
)

In [152]:
gold_product_performance["avg_cart_position"] = (
    gold_product_performance["cart_position_total"]
    /
    gold_product_performance["total_purchases"]
)

we dont need now the cart_poistion_total so we can drop it

In [153]:
gold_product_performance.drop(
    columns=["cart_position_total"],
    inplace=True
)

In [154]:
display(
    gold_product_performance
    .sort_values(
        "total_purchases",
        ascending=False
    )
    .head(20)
)

,product_id,product_name,department,aisle,total_purchases,reorder_count,reorder_rate,avg_cart_position
24849,24852,Banana,produce,fresh fruits,491291,415166,0.845051,4.896617
13173,13176,Bag of Organic Bananas,produce,fresh fruits,394930,329275,0.833755,5.082916
21134,21137,Organic Strawberries,produce,fresh fruits,275577,214448,0.778178,7.279269
21900,21903,Organic Baby Spinach,produce,packaged vegetables fruits,251705,194939,0.774474,7.431807
47205,47209,Organic Hass Avocado,produce,fresh fruits,220877,176173,0.797607,6.781544
47762,47766,Organic Avocado,produce,fresh fruits,184224,140270,0.761410,6.443536
47622,47626,Large Lemon,produce,fresh fruits,160792,112178,0.697659,7.954419
16794,16797,Strawberries,produce,fresh fruits,149445,104588,0.699843,7.130229
26206,26209,Limes,produce,fresh fruits,146660,100002,0.681863,8.598227
27842,27845,Organic Whole Milk,dairy eggs,milk,142813,118684,0.831045,5.444644
27963,27966,Organic Raspberries,produce,packaged vegetables fruits,142603,109688,0.769184,7.230170
22932,22935,Organic Yellow Onion,produce,fresh vegetables,117716,82166,0.698002,8.530200
24961,24964,Organic Garlic,produce,fresh vegetables,113936,77704,0.681997,8.791374
45004,45007,Organic Zucchini,produce,fresh vegetables,109412,75431,0.689422,9.015163
39272,39275,Organic Blueberries,produce,packaged vegetables fruits,105026,66306,0.631329,8.208187
49679,49683,Cucumber Kirby,produce,fresh vegetables,99728,69022,0.692103,7.656476
28201,28204,Organic Fuji Apple,produce,fresh fruits,92889,66237,0.713077,7.019992
5874,5876,Organic Lemon,produce,fresh fruits,91251,63046,0.690907,8.076207
40703,40706,Organic Grape Tomatoes,produce,packaged vegetables fruits,88078,57957,0.658019,9.471219
8274,8277,Apple Honeycrisp Organic,produce,fresh fruits,87272,64134,0.734875,7.675979

In [155]:
print("Number of items listed",len(gold_product_performance))

Number of items listed 49685

In [156]:
GOLD_PATH =Path("data/gold")
GOLD_PATH.mkdir(parents=True,exist_ok=True)

gold_product_performance.to_parquet(GOLD_PATH/"gold_product_performance.parquet",index=False)

gold_product_performance.to_csv(GOLD_PATH/"gold_product_performance.csv",index=False)

In [160]:
gold_department_performance=(gold_product_performance.groupby("department",as_index=False).agg(
    total_purchases=("total_purchases","sum"),
    total_reorders=("reorder_count","sum"),
    product_count=("product_id","nunique")
)
)

In [161]:
gold_department_performance["reorder_rate"]=(gold_department_performance["total_reorders"]/gold_department_performance["total_purchases"])

In [162]:
gold_department_performance["purchase_share_pct"] = (
    gold_department_performance["total_purchases"]
    /
    gold_department_performance["total_purchases"].sum()
) * 100

In [163]:
display(
    gold_department_performance
    .sort_values(
        "total_purchases",
        ascending=False
    )
)

,department,total_purchases,total_reorders,product_count,reorder_rate,purchase_share_pct
19,produce,9888378,6432596,1684,0.650521,29.239028
7,dairy eggs,5631067,3773723,3449,0.670161,16.650550
20,snacks,3006412,1727075,6264,0.574464,8.889685
3,beverages,2804175,1832952,4364,0.653651,8.291689
10,frozen,2336858,1268058,4007,0.542634,6.909875
16,pantry,1956819,679799,5370,0.347400,5.786135
2,bakery,1225181,769880,1516,0.628381,3.622748
6,canned goods,1114857,511317,2092,0.458639,3.296530
8,deli,1095540,666231,1322,0.608130,3.239411
9,dry goods pasta,905340,418466,1858,0.462220,2.677007
11,household,774652,312447,3085,0.403339,2.290575
13,meat seafood,739238,420349,907,0.568625,2.185859
4,breakfast,739069,414877,1114,0.561351,2.185359
17,personal care,468693,150855,6563,0.321863,1.385882
1,babies,438743,253453,1081,0.577680,1.297323
12,international,281155,103938,1139,0.369682,0.831350
0,alcohol,159294,90992,1054,0.571221,0.471018
18,pets,102221,61594,972,0.602557,0.302258
14,missing,77396,30519,1258,0.394323,0.228853
15,other,38086,15503,548,0.407052,0.112617
5,bulk,35932,20736,38,0.577090,0.106248

In [165]:
gold_department_performance.to_parquet(
    GOLD_PATH / "gold_department_performance.parquet",
    index=False)

gold_department_performance.to_csv(
    GOLD_PATH / "gold_department_performance.csv",
    index=False)

now we will create the final golden table for customer metrics

In [172]:
customer_parts=[]

for i,file in enumerate(analytics_files,start=1):
    df=pd.read_parquet(file,columns=
    [
        "user_id","order_id","product_id","reordered","days_since_prior_order"
    ])
    customer_summary=(
        df.groupby("user_id",as_index=False).agg(
            total_items=("product_id","count"),
            unique_products=("product_id","nunique"),
            reorder_count=("reordered","sum"),
            avg_days_between_order=("days_since_prior_order","mean")
        )
    )
    customer_parts.append(customer_summary)

    print(f"Processed file{i}/{len(analytics_files)}")

Processed file1/68
Processed file2/68
Processed file3/68
Processed file4/68
Processed file5/68
Processed file6/68
Processed file7/68
Processed file8/68
Processed file9/68
Processed file10/68
Processed file11/68
Processed file12/68
Processed file13/68
Processed file14/68
Processed file15/68
Processed file16/68
Processed file17/68
Processed file18/68
Processed file19/68
Processed file20/68
Processed file21/68
Processed file22/68
Processed file23/68
Processed file24/68
Processed file25/68
Processed file26/68
Processed file27/68
Processed file28/68
Processed file29/68
Processed file30/68
Processed file31/68
Processed file32/68
Processed file33/68
Processed file34/68
Processed file35/68
Processed file36/68
Processed file37/68
Processed file38/68
Processed file39/68
Processed file40/68
Processed file41/68
Processed file42/68
Processed file43/68
Processed file44/68
Processed file45/68
Processed file46/68
Processed file47/68
Processed file48/68
Processed file49/68
Processed file50/68
Processed file51/68
Processed file52/68
Processed file53/68
Processed file54/68
Processed file55/68
Processed file56/68
Processed file57/68
Processed file58/68
Processed file59/68
Processed file60/68
Processed file61/68
Processed file62/68
Processed file63/68
Processed file64/68
Processed file65/68
Processed file66/68
Processed file67/68
Processed file68/68

In [173]:
customer_all = pd.concat(
    customer_parts,
    ignore_index=True
)

print(customer_all.shape)

display(customer_all.head())

(2716249, 5)

,user_id,total_items,unique_products,reorder_count,avg_days_between_order
0,7,11,11,9,28.0
1,13,5,5,3,9.0
2,23,9,9,0,9.0
3,27,13,13,6,1.0
4,36,3,3,1,1.0

In [ ]:
gold_customer_metrics = (
    customer_all
    .groupby(
        "user_id",
        as_index=False
    )
    .agg(
        total_items=("total_items", "sum"),
        reorder_count=("reorder_count", "sum"),
        avg_days_between_orders=("days_since_prior_order", "mean")
    )
)

KeyError: "Label(s) ['avg_days_between_orders'] do not exist"